name: Release

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build
          run: |
            echo -e "[url \"https://github.com/\"]\n\tinsteadOf = ssh://git@github.com/" > ~/.gitconfig
            mkdir -p build
            mkdir -p static
        - uses: actions/setup-node@v1
          with:
            node-version: 10
            registry-url: 'https://npm.pkg.github.com'
            scope: '@stremio'
        - name: Publish
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
